### ISSUE TITLE
다음 4주차(10.11~10.18)에 풀이할 문제를 추천받습니다!

### ISSUE THREAD

**Issue by ChanhuiSeok** [CodeTest-StudyGroup/Code-Test-Study#51]
코딩 테스트 준비를 위해 힘쓰시는 모든 분들 힘내시면 좋겠습니다.

이번 3주차 풀이(~10.10)가 끝나면 **다음 4주차에 풀이할 4문제를 모든 분들과 함께 의견을 나누어 정하려고 합니다.**

**기간은 10월 11일 일요일이 되기 전까지, 이 이슈에 코멘트로 달아주시면 감사하겠습니다!**

추천 문제는 백준 온라인 저지 혹은 저지 시스템이 갖추어진 사이트의 문제로 추천 부탁드립니다.

아무나 많은 의견 및 추천 부탁드립니다. 감사합니다.

**Comment by ChanhuiSeok** [comment]
test

**Comment by jjangsungwon** [comment]
최근 코딩 테스트에서 그래프, 트리와 관련된 dp 문제가 자주 나오는 것 같습니다.
아래 링크에 있는 문제 중에서 1문제를 선정하면 좋을 것 같습니다.
https://www.acmicpc.net/workbook/view/897
