### ISSUE TITLE
[상시] 여기에 추천할 문제를 코멘트로 작성해 주세요!

### ISSUE THREAD

**Issue by ChanhuiSeok** [CodeTest-StudyGroup/Code-Test-Study#69]
### [상시] 여기에 추천할 문제를 코멘트로 작성해 주세요!

코딩 테스트 준비를 위해 힘쓰시는 모든 분들 힘내시면 좋겠습니다!!

모든 분들과 함께 의견을 나누어 **매주 풀이할 문제**를 정하려고 합니다.

이 이슈에 **코멘트로 추천할 문제를 링크와 함께 달아주시면** 감사하겠습니다!

추천 문제는 **백준 온라인 저지** 혹은 **저지 시스템이 갖추어진 사이트의 문제**로 추천 부탁드립니다.

추천하신 문제를 토대로 해서, 매주 진행할 문제 풀이 항목에 추가하도록 하겠습니다.

아무나 많은 의견 및 추천 부탁드립니다. 감사합니다.

**Comment by saechimdaeki** [comment]
https://www.acmicpc.net/problem/20010  악덕영주 혜유 [최근 풀었던문제로 추천]

**Comment by jjangsungwon** [comment]
https://www.acmicpc.net/problem/2593 엘리베이터

**Comment by ChanhuiSeok** [comment]
> https://www.acmicpc.net/problem/20010 악덕영주 혜유 [최근 풀었던문제로 추천]
다음 5주차 문제로 등록했습니다. 감사합니다!! 언제든 추천 주세요.

**Comment by ChanhuiSeok** [comment]
> https://www.acmicpc.net/problem/2593 엘리베이터
다음 5주차 문제로 등록했습니다. 감사합니다!! 언제든 추천 주세요.

**Comment by cheonjiwan** [comment]
https://www.acmicpc.net/problem/1854 k번째 최단경로 찾기

**Comment by ChanhuiSeok** [comment]
> https://www.acmicpc.net/problem/1854 k번째 최단경로 찾기
다음 8주차 문제로 등록했습니다. 감사합니다!! 언제든 추천 주세요.

**Comment by SeMin4** [comment]
https://www.acmicpc.net/problem/16000 섬

**Comment by ChanhuiSeok** [comment]
> https://www.acmicpc.net/problem/16000 섬
다음 8주차 문제로 등록했습니다. 감사합니다!! 언제든 추천 주세요.

**Comment by kchung1995** [comment]
https://www.acmicpc.net/problem/1111 IQ Test

**Comment by ChanhuiSeok** [comment]
> https://www.acmicpc.net/problem/1111 IQ Test
다음 12주차 문제로 등록했습니다. 감사합니다!! 언제든 추천 주세요.

**Comment by ChanhuiSeok** [comment]
Github에 새롭게 도입된 Discussion 기능으로 이전하였습니다.
